apiVersion: v1
kind: Service
metadata:
  name: url-shortener-api-service-dev
spec:
  type: NodePort
  selector:
    app: url-shortener-api-dev
  ports:
    - port: 30002
      targetPort: 8000
      nodePort: 30001
